// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Netflix.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Netflix.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260523065504_AddModule5MoviesBrowse")]
    partial class AddModule5MoviesBrowse
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Netflix.Api.Models.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<string>("SubtitleUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId", "EpisodeNumber")
                        .IsUnique();

                    b.ToTable("Episodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DurationMinutes = 48,
                            EpisodeNumber = 1,
                            SeasonId = 1,
                            SubtitleUrl = "https://raw.githubusercontent.com/mozilla/vtt.js/master/test/fixtures/webvtt-file.vtt",
                            Title = "Breach",
                            VideoUrl = "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"
                        },
                        new
                        {
                            Id = 2,
                            DurationMinutes = 51,
                            EpisodeNumber = 2,
                            SeasonId = 1,
                            SubtitleUrl = "https://raw.githubusercontent.com/mozilla/vtt.js/master/test/fixtures/webvtt-file.vtt",
                            Title = "Fallback",
                            VideoUrl = "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"
                        },
                        new
                        {
                            Id = 3,
                            DurationMinutes = 44,
                            EpisodeNumber = 1,
                            SeasonId = 2,
                            SubtitleUrl = "https://raw.githubusercontent.com/mozilla/vtt.js/master/test/fixtures/webvtt-file.vtt",
                            Title = "Neon Rain",
                            VideoUrl = "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"
                        },
                        new
                        {
                            Id = 4,
                            DurationMinutes = 46,
                            EpisodeNumber = 1,
                            SeasonId = 3,
                            SubtitleUrl = "https://raw.githubusercontent.com/mozilla/vtt.js/master/test/fixtures/webvtt-file.vtt",
                            Title = "First Signal",
                            VideoUrl = "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8"
                        });
                });

            modelBuilder.Entity("Netflix.Api.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Animation"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Documentary"
                        });
                });

            modelBuilder.Entity("Netflix.Api.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BackdropUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNetflixOriginal")
                        .HasColumnType("boolean");

                    b.Property<string>("MaturityLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PosterUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TrailerUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BackdropUrl = "https://image.tmdb.org/t/p/original/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg",
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A rogue crew infiltrates a global AI vault.",
                            IsActive = true,
                            IsNetflixOriginal = true,
                            MaturityLevel = "PG-13",
                            PosterUrl = "https://image.tmdb.org/t/p/original/8Y43POKjjKDGI9MH89NW0NAzzp8.jpg",
                            ReleaseYear = 2026,
                            Title = "Cyber Heist",
                            TrailerUrl = "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
                            ViewCount = 42110
                        },
                        new
                        {
                            Id = 2,
                            BackdropUrl = "https://image.tmdb.org/t/p/original/t5zCBSB5xMDKcDqe91qahCOUYVV.jpg",
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "An ex-agent is pulled into one last mission.",
                            IsActive = true,
                            IsNetflixOriginal = true,
                            MaturityLevel = "R",
                            PosterUrl = "https://image.tmdb.org/t/p/original/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg",
                            ReleaseYear = 2025,
                            Title = "Night Protocol",
                            TrailerUrl = "https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
                            ViewCount = 53000
                        },
                        new
                        {
                            Id = 3,
                            BackdropUrl = "https://image.tmdb.org/t/p/original/x2RS3uTcsJJ9IfjNPcgDmukoEcQ.jpg",
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Street racers battle for a city under blackout.",
                            IsActive = true,
                            IsNetflixOriginal = false,
                            MaturityLevel = "PG-13",
                            PosterUrl = "https://image.tmdb.org/t/p/original/6MKr3KgOLmzOP6MSuZERO41Lpkt.jpg",
                            ReleaseYear = 2024,
                            Title = "Skyline Rush",
                            TrailerUrl = "https://storage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
                            ViewCount = 31200
                        },
                        new
                        {
                            Id = 4,
                            BackdropUrl = "https://image.tmdb.org/t/p/original/3CxUndGhUcZdt1Zggjdb2HkLLQX.jpg",
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A violinist and chef rebuild life in Seoul.",
                            IsActive = true,
                            IsNetflixOriginal = true,
                            MaturityLevel = "PG",
                            PosterUrl = "https://image.tmdb.org/t/p/original/5a4JdoFwll5DRtKMe7JLuGQ9yJm.jpg",
                            ReleaseYear = 2023,
                            Title = "Glass Hearts",
                            TrailerUrl = "https://storage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
                            ViewCount = 20310
                        },
                        new
                        {
                            Id = 5,
                            BackdropUrl = "https://image.tmdb.org/t/p/original/wdwcOBMkt3zmPQuEMxB3FUtMio2.jpg",
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A podcast team explores a cursed highway.",
                            IsActive = true,
                            IsNetflixOriginal = false,
                            MaturityLevel = "R",
                            PosterUrl = "https://image.tmdb.org/t/p/original/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg",
                            ReleaseYear = 2022,
                            Title = "Haunted Mile",
                            TrailerUrl = "https://storage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
                            ViewCount = 18800
                        },
                        new
                        {
                            Id = 6,
                            BackdropUrl = "https://image.tmdb.org/t/p/original/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Scientists chase a signal beyond Pluto.",
                            IsActive = true,
                            IsNetflixOriginal = true,
                            MaturityLevel = "PG-13",
                            PosterUrl = "https://image.tmdb.org/t/p/original/7iiJTe7QzPoUc2zV9kib4m9fM7R.jpg",
                            ReleaseYear = 2026,
                            Title = "Planet Nine",
                            TrailerUrl = "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
                            ViewCount = 27400
                        },
                        new
                        {
                            Id = 7,
                            BackdropUrl = "https://image.tmdb.org/t/p/original/7VEUOEfRzzrQfWddlIyLUKvh6Nf.jpg",
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A failed comic turns into a viral sensation.",
                            IsActive = true,
                            IsNetflixOriginal = false,
                            MaturityLevel = "PG-13",
                            PosterUrl = "https://image.tmdb.org/t/p/original/3h1JZGDhZ8nzxdgvkxha0qBqi05.jpg",
                            ReleaseYear = 2025,
                            Title = "Laugh Track",
                            TrailerUrl = "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
                            ViewCount = 16600
                        },
                        new
                        {
                            Id = 8,
                            BackdropUrl = "https://image.tmdb.org/t/p/original/cWczNud8Y8i8ab0Z4A8kJ6X1T4F.jpg",
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A brave kid befriends a hidden dragon hatchling.",
                            IsActive = true,
                            IsNetflixOriginal = true,
                            MaturityLevel = "PG",
                            PosterUrl = "https://image.tmdb.org/t/p/original/hwlyY7Jw5M3M6bMFD4kK5Jz2W6G.jpg",
                            ReleaseYear = 2021,
                            Title = "Tiny Dragons",
                            TrailerUrl = "https://storage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
                            ViewCount = 32050
                        },
                        new
                        {
                            Id = 9,
                            BackdropUrl = "https://image.tmdb.org/t/p/original/8YFL5QQVPy3AgrEQxNYVSgiPEbe.jpg",
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Three chefs, one brutal cooking tournament.",
                            IsActive = true,
                            IsNetflixOriginal = false,
                            MaturityLevel = "PG",
                            PosterUrl = "https://image.tmdb.org/t/p/original/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg",
                            ReleaseYear = 2020,
                            Title = "Kitchen Wars",
                            TrailerUrl = "https://storage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4",
                            ViewCount = 11020
                        },
                        new
                        {
                            Id = 10,
                            BackdropUrl = "https://image.tmdb.org/t/p/original/euXQw5nB8Jt3Q5GsyhQOdE31E4n.jpg",
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A research station vanishes under polar ice.",
                            IsActive = true,
                            IsNetflixOriginal = true,
                            MaturityLevel = "PG-13",
                            PosterUrl = "https://image.tmdb.org/t/p/original/6Zx6mP4QEtBfV63P2QxY8fJfN7K.jpg",
                            ReleaseYear = 2024,
                            Title = "Undersea 47",
                            TrailerUrl = "https://storage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
                            ViewCount = 23100
                        },
                        new
                        {
                            Id = 11,
                            BackdropUrl = "https://image.tmdb.org/t/p/original/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg",
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A detective hunts a ghost hacker in Tokyo.",
                            IsActive = true,
                            IsNetflixOriginal = true,
                            MaturityLevel = "TV-14",
                            PosterUrl = "https://image.tmdb.org/t/p/original/2uNW4WbgBXL25BAbXGLnLqX71Sw.jpg",
                            ReleaseYear = 2026,
                            Title = "Neon District",
                            TrailerUrl = "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
                            ViewCount = 49810
                        },
                        new
                        {
                            Id = 12,
                            BackdropUrl = "https://image.tmdb.org/t/p/original/u3TJVMY67S6WKL7f3qF2zH2M4k4.jpg",
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Teens uncover secrets in an abandoned camp.",
                            IsActive = true,
                            IsNetflixOriginal = false,
                            MaturityLevel = "PG-13",
                            PosterUrl = "https://image.tmdb.org/t/p/original/5a4JdoFwll5DRtKMe7JLuGQ9yJm.jpg",
                            ReleaseYear = 2023,
                            Title = "The Last Summer Camp",
                            TrailerUrl = "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
                            ViewCount = 15620
                        },
                        new
                        {
                            Id = 13,
                            BackdropUrl = "https://image.tmdb.org/t/p/original/Akg1NnK8N2w4bYY6Y9A6kzI3H7J.jpg",
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Politics and survival on humanity's first moon city.",
                            IsActive = true,
                            IsNetflixOriginal = true,
                            MaturityLevel = "TV-14",
                            PosterUrl = "https://image.tmdb.org/t/p/original/4Q1n3TwieoULnuaztu9aFjqHDTI.jpg",
                            ReleaseYear = 2025,
                            Title = "Moon Colony",
                            TrailerUrl = "https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
                            ViewCount = 39005
                        },
                        new
                        {
                            Id = 14,
                            BackdropUrl = "https://image.tmdb.org/t/p/original/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg",
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Two strangers relive one day in different timelines.",
                            IsActive = true,
                            IsNetflixOriginal = false,
                            MaturityLevel = "PG",
                            PosterUrl = "https://image.tmdb.org/t/p/original/8Y43POKjjKDGI9MH89NW0NAzzp8.jpg",
                            ReleaseYear = 2022,
                            Title = "Parallel Hearts",
                            TrailerUrl = "https://storage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
                            ViewCount = 14011
                        },
                        new
                        {
                            Id = 15,
                            BackdropUrl = "https://image.tmdb.org/t/p/original/t5zCBSB5xMDKcDqe91qahCOUYVV.jpg",
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A drone race turns into a treasure hunt.",
                            IsActive = true,
                            IsNetflixOriginal = true,
                            MaturityLevel = "PG",
                            PosterUrl = "https://image.tmdb.org/t/p/original/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg",
                            ReleaseYear = 2026,
                            Title = "Jungle Circuit",
                            TrailerUrl = "https://storage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
                            ViewCount = 22400
                        },
                        new
                        {
                            Id = 16,
                            BackdropUrl = "https://image.tmdb.org/t/p/original/x2RS3uTcsJJ9IfjNPcgDmukoEcQ.jpg",
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A journalist vanishes after decoding a satellite feed.",
                            IsActive = true,
                            IsNetflixOriginal = false,
                            MaturityLevel = "R",
                            PosterUrl = "https://image.tmdb.org/t/p/original/6MKr3KgOLmzOP6MSuZERO41Lpkt.jpg",
                            ReleaseYear = 2021,
                            Title = "Signal Lost",
                            TrailerUrl = "https://storage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
                            ViewCount = 17990
                        },
                        new
                        {
                            Id = 17,
                            BackdropUrl = "https://image.tmdb.org/t/p/original/7VEUOEfRzzrQfWddlIyLUKvh6Nf.jpg",
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Astronaut cadets face sabotage during final exam.",
                            IsActive = true,
                            IsNetflixOriginal = true,
                            MaturityLevel = "PG-13",
                            PosterUrl = "https://image.tmdb.org/t/p/original/3h1JZGDhZ8nzxdgvkxha0qBqi05.jpg",
                            ReleaseYear = 2024,
                            Title = "Zero Gravity",
                            TrailerUrl = "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
                            ViewCount = 27001
                        },
                        new
                        {
                            Id = 18,
                            BackdropUrl = "https://image.tmdb.org/t/p/original/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A watchmaker discovers a clock that rewinds fate.",
                            IsActive = true,
                            IsNetflixOriginal = false,
                            MaturityLevel = "PG-13",
                            PosterUrl = "https://image.tmdb.org/t/p/original/7iiJTe7QzPoUc2zV9kib4m9fM7R.jpg",
                            ReleaseYear = 2023,
                            Title = "Borrowed Time",
                            TrailerUrl = "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
                            ViewCount = 13888
                        },
                        new
                        {
                            Id = 19,
                            BackdropUrl = "https://image.tmdb.org/t/p/original/wdwcOBMkt3zmPQuEMxB3FUtMio2.jpg",
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A masked vigilante sparks a rebellion.",
                            IsActive = true,
                            IsNetflixOriginal = false,
                            MaturityLevel = "TV-14",
                            PosterUrl = "https://image.tmdb.org/t/p/original/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg",
                            ReleaseYear = 2020,
                            Title = "City of Masks",
                            TrailerUrl = "https://storage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
                            ViewCount = 12499
                        },
                        new
                        {
                            Id = 20,
                            BackdropUrl = "https://image.tmdb.org/t/p/original/8YFL5QQVPy3AgrEQxNYVSgiPEbe.jpg",
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A family road trip through forgotten observatories.",
                            IsActive = true,
                            IsNetflixOriginal = false,
                            MaturityLevel = "PG",
                            PosterUrl = "https://image.tmdb.org/t/p/original/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg",
                            ReleaseYear = 2019,
                            Title = "Planetarium",
                            TrailerUrl = "https://storage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4",
                            ViewCount = 9650
                        },
                        new
                        {
                            Id = 21,
                            BackdropUrl = "https://image.tmdb.org/t/p/original/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg",
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kids solve mysteries in a mountain village.",
                            IsActive = true,
                            IsNetflixOriginal = true,
                            MaturityLevel = "G",
                            PosterUrl = "https://image.tmdb.org/t/p/original/2uNW4WbgBXL25BAbXGLnLqX71Sw.jpg",
                            ReleaseYear = 2022,
                            Title = "Campfire Club",
                            TrailerUrl = "https://storage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
                            ViewCount = 19080
                        },
                        new
                        {
                            Id = 22,
                            BackdropUrl = "https://image.tmdb.org/t/p/original/Akg1NnK8N2w4bYY6Y9A6kzI3H7J.jpg",
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Two app engineers fake date to save their startup.",
                            IsActive = true,
                            IsNetflixOriginal = true,
                            MaturityLevel = "PG-13",
                            PosterUrl = "https://image.tmdb.org/t/p/original/4Q1n3TwieoULnuaztu9aFjqHDTI.jpg",
                            ReleaseYear = 2026,
                            Title = "404 Love Not Found",
                            TrailerUrl = "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
                            ViewCount = 25003
                        },
                        new
                        {
                            Id = 23,
                            BackdropUrl = "https://image.tmdb.org/t/p/original/3CxUndGhUcZdt1Zggjdb2HkLLQX.jpg",
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A deaf composer hears signals from the future.",
                            IsActive = true,
                            IsNetflixOriginal = true,
                            MaturityLevel = "PG-13",
                            PosterUrl = "https://image.tmdb.org/t/p/original/5a4JdoFwll5DRtKMe7JLuGQ9yJm.jpg",
                            ReleaseYear = 2025,
                            Title = "Dawn of Echoes",
                            TrailerUrl = "https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
                            ViewCount = 21070
                        },
                        new
                        {
                            Id = 24,
                            BackdropUrl = "https://image.tmdb.org/t/p/original/euXQw5nB8Jt3Q5GsyhQOdE31E4n.jpg",
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A train heist crosses three countries overnight.",
                            IsActive = true,
                            IsNetflixOriginal = false,
                            MaturityLevel = "R",
                            PosterUrl = "https://image.tmdb.org/t/p/original/6Zx6mP4QEtBfV63P2QxY8fJfN7K.jpg",
                            ReleaseYear = 2024,
                            Title = "Red Corridor",
                            TrailerUrl = "https://storage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
                            ViewCount = 28776
                        },
                        new
                        {
                            Id = 25,
                            BackdropUrl = "https://image.tmdb.org/t/p/original/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg",
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A coder races to stop a financial AI meltdown.",
                            IsActive = true,
                            IsNetflixOriginal = true,
                            MaturityLevel = "TV-14",
                            PosterUrl = "https://image.tmdb.org/t/p/original/8Y43POKjjKDGI9MH89NW0NAzzp8.jpg",
                            ReleaseYear = 2026,
                            Title = "Runaway Algorithm",
                            TrailerUrl = "https://storage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
                            ViewCount = 37741
                        },
                        new
                        {
                            Id = 26,
                            BackdropUrl = "https://image.tmdb.org/t/p/original/t5zCBSB5xMDKcDqe91qahCOUYVV.jpg",
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Artists revive a forgotten riverside town.",
                            IsActive = true,
                            IsNetflixOriginal = false,
                            MaturityLevel = "PG",
                            PosterUrl = "https://image.tmdb.org/t/p/original/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg",
                            ReleaseYear = 2021,
                            Title = "Paper Lanterns",
                            TrailerUrl = "https://storage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
                            ViewCount = 10031
                        },
                        new
                        {
                            Id = 27,
                            BackdropUrl = "https://image.tmdb.org/t/p/original/x2RS3uTcsJJ9IfjNPcgDmukoEcQ.jpg",
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Divers discover a city beneath volcanic vents.",
                            IsActive = true,
                            IsNetflixOriginal = true,
                            MaturityLevel = "PG-13",
                            PosterUrl = "https://image.tmdb.org/t/p/original/6MKr3KgOLmzOP6MSuZERO41Lpkt.jpg",
                            ReleaseYear = 2020,
                            Title = "Deep Current",
                            TrailerUrl = "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
                            ViewCount = 15321
                        },
                        new
                        {
                            Id = 28,
                            BackdropUrl = "https://image.tmdb.org/t/p/original/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A teen spy infiltrates a private academy.",
                            IsActive = true,
                            IsNetflixOriginal = false,
                            MaturityLevel = "PG",
                            PosterUrl = "https://image.tmdb.org/t/p/original/7iiJTe7QzPoUc2zV9kib4m9fM7R.jpg",
                            ReleaseYear = 2023,
                            Title = "Code Name Kite",
                            TrailerUrl = "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
                            ViewCount = 16222
                        },
                        new
                        {
                            Id = 29,
                            BackdropUrl = "https://image.tmdb.org/t/p/original/7VEUOEfRzzrQfWddlIyLUKvh6Nf.jpg",
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A music teacher starts a jungle orchestra.",
                            IsActive = true,
                            IsNetflixOriginal = false,
                            MaturityLevel = "G",
                            PosterUrl = "https://image.tmdb.org/t/p/original/3h1JZGDhZ8nzxdgvkxha0qBqi05.jpg",
                            ReleaseYear = 2018,
                            Title = "Wild Notes",
                            TrailerUrl = "https://storage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
                            ViewCount = 8120
                        },
                        new
                        {
                            Id = 30,
                            BackdropUrl = "https://image.tmdb.org/t/p/original/wdwcOBMkt3zmPQuEMxB3FUtMio2.jpg",
                            CreatedAt = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A radio host receives calls from alternate realities.",
                            IsActive = true,
                            IsNetflixOriginal = true,
                            MaturityLevel = "TV-14",
                            PosterUrl = "https://image.tmdb.org/t/p/original/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg",
                            ReleaseYear = 2022,
                            Title = "After Midnight",
                            TrailerUrl = "https://storage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4",
                            ViewCount = 22229
                        });
                });

            modelBuilder.Entity("Netflix.Api.Models.MovieGenre", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.HasKey("MovieId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("MovieGenres");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 1,
                            GenreId = 4
                        },
                        new
                        {
                            MovieId = 2,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 2,
                            GenreId = 2
                        },
                        new
                        {
                            MovieId = 3,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 3,
                            GenreId = 3
                        },
                        new
                        {
                            MovieId = 4,
                            GenreId = 2
                        },
                        new
                        {
                            MovieId = 4,
                            GenreId = 6
                        },
                        new
                        {
                            MovieId = 5,
                            GenreId = 5
                        },
                        new
                        {
                            MovieId = 5,
                            GenreId = 2
                        },
                        new
                        {
                            MovieId = 6,
                            GenreId = 4
                        },
                        new
                        {
                            MovieId = 6,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 7,
                            GenreId = 3
                        },
                        new
                        {
                            MovieId = 7,
                            GenreId = 2
                        },
                        new
                        {
                            MovieId = 8,
                            GenreId = 7
                        },
                        new
                        {
                            MovieId = 8,
                            GenreId = 6
                        },
                        new
                        {
                            MovieId = 9,
                            GenreId = 3
                        },
                        new
                        {
                            MovieId = 9,
                            GenreId = 8
                        },
                        new
                        {
                            MovieId = 10,
                            GenreId = 4
                        },
                        new
                        {
                            MovieId = 10,
                            GenreId = 5
                        },
                        new
                        {
                            MovieId = 11,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 11,
                            GenreId = 4
                        },
                        new
                        {
                            MovieId = 12,
                            GenreId = 2
                        },
                        new
                        {
                            MovieId = 12,
                            GenreId = 5
                        },
                        new
                        {
                            MovieId = 13,
                            GenreId = 4
                        },
                        new
                        {
                            MovieId = 13,
                            GenreId = 2
                        },
                        new
                        {
                            MovieId = 14,
                            GenreId = 6
                        },
                        new
                        {
                            MovieId = 14,
                            GenreId = 2
                        },
                        new
                        {
                            MovieId = 15,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 15,
                            GenreId = 7
                        },
                        new
                        {
                            MovieId = 16,
                            GenreId = 5
                        },
                        new
                        {
                            MovieId = 16,
                            GenreId = 2
                        },
                        new
                        {
                            MovieId = 17,
                            GenreId = 4
                        },
                        new
                        {
                            MovieId = 17,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 18,
                            GenreId = 2
                        },
                        new
                        {
                            MovieId = 18,
                            GenreId = 4
                        },
                        new
                        {
                            MovieId = 19,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 19,
                            GenreId = 2
                        },
                        new
                        {
                            MovieId = 20,
                            GenreId = 8
                        },
                        new
                        {
                            MovieId = 20,
                            GenreId = 6
                        },
                        new
                        {
                            MovieId = 21,
                            GenreId = 7
                        },
                        new
                        {
                            MovieId = 21,
                            GenreId = 2
                        },
                        new
                        {
                            MovieId = 22,
                            GenreId = 3
                        },
                        new
                        {
                            MovieId = 22,
                            GenreId = 6
                        },
                        new
                        {
                            MovieId = 23,
                            GenreId = 2
                        },
                        new
                        {
                            MovieId = 23,
                            GenreId = 4
                        },
                        new
                        {
                            MovieId = 24,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 24,
                            GenreId = 5
                        },
                        new
                        {
                            MovieId = 25,
                            GenreId = 4
                        },
                        new
                        {
                            MovieId = 25,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 26,
                            GenreId = 2
                        },
                        new
                        {
                            MovieId = 26,
                            GenreId = 8
                        },
                        new
                        {
                            MovieId = 27,
                            GenreId = 4
                        },
                        new
                        {
                            MovieId = 27,
                            GenreId = 8
                        },
                        new
                        {
                            MovieId = 28,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 28,
                            GenreId = 7
                        },
                        new
                        {
                            MovieId = 29,
                            GenreId = 7
                        },
                        new
                        {
                            MovieId = 29,
                            GenreId = 3
                        },
                        new
                        {
                            MovieId = 30,
                            GenreId = 5
                        },
                        new
                        {
                            MovieId = 30,
                            GenreId = 4
                        });
                });

            modelBuilder.Entity("Netflix.Api.Models.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsKids")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PinCode")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Netflix.Api.Models.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("MovieId", "SeasonNumber")
                        .IsUnique();

                    b.ToTable("Seasons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MovieId = 1,
                            SeasonNumber = 1,
                            Title = "Season 1"
                        },
                        new
                        {
                            Id = 2,
                            MovieId = 11,
                            SeasonNumber = 1,
                            Title = "Season 1"
                        },
                        new
                        {
                            Id = 3,
                            MovieId = 13,
                            SeasonNumber = 1,
                            Title = "Season 1"
                        });
                });

            modelBuilder.Entity("Netflix.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSubscribed")
                        .HasColumnType("boolean");

                    b.Property<string>("OtpCode")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTime?>("OtpExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubscriptionPlan")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerificationToken")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Netflix.Api.Models.WatchHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastWatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("TimestampSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("MovieId");

                    b.HasIndex("ProfileId", "MovieId", "EpisodeId");

                    b.ToTable("WatchHistories");
                });

            modelBuilder.Entity("Netflix.Api.Models.Episode", b =>
                {
                    b.HasOne("Netflix.Api.Models.Season", "Season")
                        .WithMany("Episodes")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Netflix.Api.Models.MovieGenre", b =>
                {
                    b.HasOne("Netflix.Api.Models.Genre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Netflix.Api.Models.Movie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Netflix.Api.Models.Profile", b =>
                {
                    b.HasOne("Netflix.Api.Models.User", "User")
                        .WithMany("Profiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Netflix.Api.Models.Season", b =>
                {
                    b.HasOne("Netflix.Api.Models.Movie", "Movie")
                        .WithMany("Seasons")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Netflix.Api.Models.WatchHistory", b =>
                {
                    b.HasOne("Netflix.Api.Models.Episode", "Episode")
                        .WithMany("WatchHistories")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Netflix.Api.Models.Movie", "Movie")
                        .WithMany("WatchHistories")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Netflix.Api.Models.Profile", "Profile")
                        .WithMany("WatchHistories")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Episode");

                    b.Navigation("Movie");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Netflix.Api.Models.Episode", b =>
                {
                    b.Navigation("WatchHistories");
                });

            modelBuilder.Entity("Netflix.Api.Models.Genre", b =>
                {
                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("Netflix.Api.Models.Movie", b =>
                {
                    b.Navigation("MovieGenres");

                    b.Navigation("Seasons");

                    b.Navigation("WatchHistories");
                });

            modelBuilder.Entity("Netflix.Api.Models.Profile", b =>
                {
                    b.Navigation("WatchHistories");
                });

            modelBuilder.Entity("Netflix.Api.Models.Season", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("Netflix.Api.Models.User", b =>
                {
                    b.Navigation("Profiles");
                });
#pragma warning restore 612, 618
        }
    }
}
